name: EnderaLib
version: 1.4.3
main: org.endera.enderalib.EnderaLib
api-version: '1.18'
authors: [EnderaDev]
folia-supported: true
commands:
  enderalib:
    description: Get info about plugin version
    usage: /<command> version