name: EnderaLib
version: 1.0-SNAPSHOT
main: org.endera.enderalib.EnderaLib
api-version: '1.18'
authors: [EnderaDev]
commands:
  enderalib:
    description: Get info about plugin version
    usage: /<command> version