name: EnderaLib
version: ${version}
main: org.endera.enderalib.EnderaLib
api-version: '1.18'
authors: [EnderaDev]
folia-supported: true
libraries:
${libraries}
commands:
  enderalib:
    description: Get info about plugin version
    usage: /<command> version
