name: EnderaLib
version: ${projectVersion}
main: org.endera.enderalib.EnderaLib
api-version: '1.17'
authors: [EnderaDev]
commands:
  enderalib:
    description: Получить информацию о версии плагина
    usage: /<command> version